export const SAVE_CATEGORIE_REQUEST = "SAVE_CATEGORIE_REQUEST";
export const DELETE_CATEGORIE_REQUEST = "DELETE_CATEGORIE_REQUEST";
export const CATEGORIE_SUCCESS = "CATEGORIE_SUCCESS";
export const CATEGORIE_FAILURE = "CATEGORIE_FAILURE";
